### PR TITLE
Feat/Customization

### LINKED ISSUE #12: Text "Double click to create new node" should be optional
The text "Double click to create new node" is appearing at the bottom of my tree. I don't see an option to remove it, but it should be optional not required.

### PR DESCRIPTION
**Pull request by phenry20**
* Icons can now be added per node
* Non links now show default cursor
* Links with child nodes have to be expanded using the +/- buttons

### CODE REVIEW

**Review by ll931217 — APPROVED** [review]

**Review by ll931217 — COMMENTED** [review]
I will be fixing up the changes to them.

**Comment by phenry20** [comment]
I've added a fix to allow node to be clickable

**Comment by phenry20** [comment]
> image
> Your change gives the node 2 icons, the parent node shouldn't have an icon besides `plus` and `minus`. I have also realised that with these changes, the node without a link shouldn't even have an icon but it is showing icons and also double clicking these nodes does not bring up the create new node modal.

For an application like mine I want the icon to show if it has been specified. Users should be given the option whether they want an icon there or not.  

Also I completely forgot about the create new node modal window. Personally I think how that modal shows up should be configurable or possibly removed. I could be wrong, but I believe most users would have their own system in place for adding new items to the tree.

**Comment by phenry20** [comment]
Screen Shot 2020-03-24 at 9 34 08 PM

With your latest change, when I have a parent node it doesn't recognize the link (I'm unable to click on the text) and the icon doesn't show :(

**Comment by ll931217** [comment]
> Screen Shot 2020-03-24 at 9 34 08 PM
> 
> With your latest change, when I have a parent node it doesn't recognize the link or the icon :(

Hey, can I see what your JSON looks like?

**Comment by ll931217** [comment]
> > image
> > Your change gives the node 2 icons, the parent node shouldn't have an icon besides `plus` and `minus`. I have also realised that with these changes, the node without a link shouldn't even have an icon but it is showing icons and also double clicking these nodes does not bring up the create new node modal.
> 
> For an application like mine, having an icon beside the `plus` and `minus` is necessary, but I agree that the default icon shouldn't be there if none is specified.
> 
> I've never used pug before so sorry if the changes aren't great, I'm just trying to get things working for my needs while making it flexible for others as well.

Hmmm I can see a possible use case for the icons to be optional for parent nodes.

**Comment by phenry20** [comment]
> > Screen Shot 2020-03-24 at 9 34 08 PM
> > With your latest change, when I have a parent node it doesn't recognize the link or the icon :(
> 
> Hey, can I see what your JSON looks like?


```js
[
  {
    "text": "Standing Up",
    "link": {
      "type": "router-link",
      "key": "path",
      "value": "templink"
    },
    "icon": "cube",
    "nodes": [
      {
        "text": "mixamo.com",
        "link": {
          "type": "router-link",
          "key": "path",
          "value": "templink"
        },
        "icon": "running"
      }
    ]
  }
]
```

**Comment by ll931217** [comment]
> > > Screen Shot 2020-03-24 at 9 34 08 PM
> > > With your latest change, when I have a parent node it doesn't recognize the link or the icon :(
> > 
> > 
> > Hey, can I see what your JSON looks like?
> 
> ```js
> [
>   {
>     "text": "Standing Up",
>     "link": {
>       "type": "router-link",
>       "key": "path",
>       "value": "templink"
>     },
>     "icon": "cube",
>     "nodes": [
>       {
>         "text": "mixamo.com",
>         "link": {
>           "type": "router-link",
>           "key": "path",
>           "value": "templink"
>         },
>         "icon": "running"
>       }
>     ]
>   }
> ]
> ```

Hmmm I am not able to recreate your issue
image

I didn't make it so the parent node can be a link, but I think that can also be implemented in future releases.

**Comment by phenry20** [comment]
> > > > Screen Shot 2020-03-24 at 9 34 08 PM
> > > > With your latest change, when I have a parent node it doesn't recognize the link or the icon :(
> > > 
> > > 
> > > Hey, can I see what your JSON looks like?
> > 
> > 
> > ```js
> > [
> >   {
> >     "text": "Standing Up",
> >     "link": {
> >       "type": "router-link",
> >       "key": "path",
> >       "value": "templink"
> >     },
> >     "icon": "cube",
> >     "nodes": [
> >       {
> >         "text": "mixamo.com",
> >         "link": {
> >           "type": "router-link",
> >           "key": "path",
> >           "value": "templink"
> >         },
> >         "icon": "running"
> >       }
> >     ]
> >   }
> > ]
> > ```
> 
> Hmmm I am not able to recreate your issue
> image

Hmm that's odd. Do you have the latest changes on this branch?

On my project I used `yarn add https://github.com/phenry20/vue-treeview#feat/icons` to get the latest changes on this branch so I'm not sure why I'm getting different behaviour, but apart from the link issue the icon still isn't showing which I need it to.

**Comment by phenry20** [comment]
Oh wait. I realize where the mixup is. I added custom styling to my tree. As you can see the link is working for children, but I need the link to work for root nodes as well. 

In the picture you showed above "Standing Up" is in white text, but it should be in "blue" text because it has a link

**Comment by ll931217** [comment]
Hey, so I added a `show-parent-icon` prop option, this takes an `Object`, by default all options will be false to not show the icons on parent nodes. I have 2 options so far:

`parentShow`: is for parent nodes with child nodes available.
`emptyParentShow`: is for empty parent nodes.

I am thinking that maybe I should add in a default icon for those two types of parent nodes.

```javascript
showParentIcon: {
  type: Object,
  default: () => ({
    parentShow: false,
    emptyParentShow: false
  })
}
```

**Comment by phenry20** [comment]
> Hey, so I added a `show-parent-icon` prop option, this takes an `Object`, by default all options will be false to not show the icons on parent nodes. I have 2 options so far:
> 
> `parentShow`: is for parent nodes with child nodes available.
> `emptyParentShow`: is for empty parent nodes.
> 
> I am thinking that maybe I should add in a default icon for those two types of parent nodes.
> 
> ```js
> showParentIcon: {
>   type: Object,
>   default: () => ({
>     parentShow: false,
>     emptyParentShow: false
>   })
> }
> ```

Tbh I don't think default icons are necessary. If the user wants a default icon they can just add it to their json object

**Comment by ll931217** [comment]
Hello, please check the latest commit.

If the parent node has a `link` object, it should become a link, the icon of this parent node won't be affected by the `showParentIcon` prop.

**Comment by phenry20** [comment]
Screen Shot 2020-03-25 at 10 40 32 AM

The links now work, but icons are no longer showing for children without links

**Comment by ll931217** [comment]
Can I see your prop option?

**Comment by phenry20** [comment]
> Can I see your prop option?

Nvm. I realized that my props were wrong. I didn't realized that emptyParentShow and parentShow were children of showParentIcon. Everything works as intended :)

**Comment by ll931217** [comment]
Well, let me know if you are satisfied with the changes. I will update the `README.md`, then merge the PR

**Comment by phenry20** [comment]
I'm satisfied. Everything works as intended.

**Pull request merged**
